In [1]:
import cv2
import numpy as np
import matplotlib
import math
from matplotlib import pyplot as plt
%matplotlib inline  

In [2]:
images_name = ['./imgs/target.jpg']
images = []
for img_name in images_name:
    img = cv2.imread(img_name)
    images.append(img)

imgpoints = ([2270.7, 881.3],
            [2404.7, 908.7],
            [2531.3, 930],
            [2283.3, 1060],
            [2413.3, 1080],
            [2542.7, 1100],
            [2292, 1243.3],
            [2425.3, 1256.7],
            [2552, 1270],
            [2306.7, 1427.3],
            [2436.7, 1434.7],
            [2566.7, 1440.7],
            [2320, 1616],
            [2458.7, 1616.7],
            [2579.3, 1616.7],
            [1938.7, 906],
            [1828, 945],
            [1712.7, 986.7],
            [1952.7, 1082],
            [1834, 1120.7],
            [1728.7, 1152],
            [1954.7, 1266.7],
            [1848, 1296.7],
            [1736, 1328],
            [1965.3, 1451.3],
            [1847.3, 1476],
            [1738.7, 1498]
            )
# worldpoints = ([0,0,0],
#             [20,0,0],
#             [40,0,0],
#             [0,20,0],
#             [20,20,0],
#             [40,20,0],
#             [0,40,0],
#             [20,40,0],
#             [40,40,0],
#             [0,60,0],
#             [20,60,0],
#             [40,60,0],
#             [0,80,0],
#             [20,80,0],
#             [40,80,0],
#             [-27.2,0,-24.5],
#             [-27.2,0,-44.5],
#             [-27.2,0,-64.5],
#             [-27.2,20,-24.5],
#             [-27.2,20,-44.5],
#             [-27.2,20,-64.5],
#             [-27.2,40,-24.5],
#             [-27.2,40,-44.5],
#             [-27.2,40,-64.5],
#             [-27.2,60,-24.5],
#             [-27.2,60,-44.5],
#             [-27.2,60,-64.5])

worldpoints = ([27.2,0,80],
            [47.2,0,80],
            [67.2,0,80],
            [27.2,0,60],
            [47.2,0,60],
            [67.2,0,60],
            [27.2,0,40],
            [47.2,0,40],
            [67.2,0,40],
            [27.2,0,20],
            [47.2,0,20],
            [67.2,0,20],
            [27.2,0,0],
            [47.2,0,0],
            [67.2,0,0],
            [0,24.5,80],
            [0,44.5,80],
            [0,64.5,80],
            [0,24.5,60],
            [0,44.5,60],
            [0,64.5,60],
            [0,24.5,40],
            [0,44.5,40],
            [0,64.5,40],
            [0,24.5,20],
            [0,44.5,20],
            [0,64.5,20]
              )

worldpoints = np.asarray(worldpoints)
# cv2.circle(images[0],(imgpoints[0][0],imgpoints[0][1]),50,(0,0,255),-1)#0,0
# cv2.putText(images[0],str(worldpoints[0]),(imgpoints[0][0],imgpoints[0][1]), cv2.FONT_HERSHEY_SIMPLEX, 5,(0,0,255),15,cv2.LINE_AA)
# cv2.circle(images[0],(imgpoints[-1][0],imgpoints[-1][1]),50,(255,0,0),-1)#fim,fim
# cv2.circle(images[0],(imgpoints[14][0],imgpoints[14][1]),50,(0,0,255),-1)#0,0
# cv2.circle(images[0],(imgpoints[15][0],imgpoints[15][1]),50,(255,0,0),-1)#fim,fim
# cv2.putText(images[0],str(worldpoints[-1]),(imgpoints[-1][0],imgpoints[-1][1]), cv2.FONT_HERSHEY_SIMPLEX, 5,(0,0,255),15,cv2.LINE_AA)
# plt.imshow(cv2.cvtColor(images[0], cv2.COLOR_BGR2RGB))
# plt.show()

In [3]:
A = []
for worldpoint, imagepoint in zip(worldpoints, imgpoints):
    print(worldpoint, imagepoint)
    A_line = []
    A_line.append(imagepoint[0] * worldpoint[0])
    A_line.append(imagepoint[0] * worldpoint[1])
    A_line.append(imagepoint[0] * worldpoint[2])
    A_line.append(imagepoint[0])
    A_line.append(-imagepoint[1] * worldpoint[0])
    A_line.append(-imagepoint[1] * worldpoint[1])
    A_line.append(-imagepoint[1] * worldpoint[2])
    A_line.append(-imagepoint[1])
    A.append(A_line)
A = np.asarray(A)


[27.2  0.  80. ] [2270.7, 881.3]
[47.2  0.  80. ] [2404.7, 908.7]
[67.2  0.  80. ] [2531.3, 930]
[27.2  0.  60. ] [2283.3, 1060]
[47.2  0.  60. ] [2413.3, 1080]
[67.2  0.  60. ] [2542.7, 1100]
[27.2  0.  40. ] [2292, 1243.3]
[47.2  0.  40. ] [2425.3, 1256.7]
[67.2  0.  40. ] [2552, 1270]
[27.2  0.  20. ] [2306.7, 1427.3]
[47.2  0.  20. ] [2436.7, 1434.7]
[67.2  0.  20. ] [2566.7, 1440.7]
[27.2  0.   0. ] [2320, 1616]
[47.2  0.   0. ] [2458.7, 1616.7]
[67.2  0.   0. ] [2579.3, 1616.7]
[ 0.  24.5 80. ] [1938.7, 906]
[ 0.  44.5 80. ] [1828, 945]
[ 0.  64.5 80. ] [1712.7, 986.7]
[ 0.  24.5 60. ] [1952.7, 1082]
[ 0.  44.5 60. ] [1834, 1120.7]
[ 0.  64.5 60. ] [1728.7, 1152]
[ 0.  24.5 40. ] [1954.7, 1266.7]
[ 0.  44.5 40. ] [1848, 1296.7]
[ 0.  64.5 40. ] [1736, 1328]
[ 0.  24.5 20. ] [1965.3, 1451.3]
[ 0.  44.5 20. ] [1847.3, 1476]
[ 0.  64.5 20. ] [1738.7, 1498]


In [4]:
U, D, V = np.linalg.svd(A, full_matrices=True)
# print(np.transpose(V))
# print(D)
# print (U.shape, D.shape, V.shape)
# print(np.linalg.eig(A))
# print(np.linalg.matrix_rank(A))
minSingValue = np.argmin(D)
print(D)
V_selected = V[minSingValue]
for idx, v in enumerate(V):
    print ("V[{}]".format(idx))
    print(np.dot(A, v))

# print(V,V_selected)

[7.63421117e+05 4.42913929e+05 2.26799368e+05 3.84615260e+04
 2.16074072e+04 1.71757497e+04 2.24485728e+03 1.00570068e+01]
V[0]
[-192486.69734137 -231780.94978129 -273110.0430143  -159276.32410264
 -196936.42709645 -237379.64254762 -123147.65814705 -159779.78905281
 -198826.25882517  -84399.73702881 -119822.73942864 -157920.50536094
  -42682.9611912   -77363.11180079 -114233.84583828 -147899.95392363
 -150887.19646128 -153043.11100924 -118506.42015936 -122852.48670168
 -127055.84459859  -86010.87051801  -92502.75484185  -98187.61660029
  -51051.38840241  -59015.35720927  -66458.19384283]
V[1]
[  18432.25787852  -17105.51084058  -56200.41702074    2640.09333377
  -35065.83157804  -76297.2681357   -14768.40090853  -54659.67787293
  -97877.7493399   -33879.40667838  -75866.24334997 -121194.61145704
  -54713.07392361  -99067.56048001 -146136.49776912   89800.79727105
  111683.56365712  131718.92681038   79256.6517423   102600.46657746
  124485.0777987    66947.33641673   92256.42198987  11

In [5]:
gamma = math.sqrt((V_selected[0]**2)+(V_selected[1]**2)+(V_selected[2]**2))
alfa = math.sqrt((V_selected[4]**2)+(V_selected[5]**2)+(V_selected[6]**2))/gamma
print (gamma,alfa)

0.003910468204803878 1.110026329255483


In [6]:
r = np.ones(shape=(3,3))
t = np.ones(shape=(3,1))
r[1][0] = V_selected[0]/gamma
r[1][1] = V_selected[1]/gamma
r[1][2] = V_selected[2]/gamma
t[1] = V_selected[3]/gamma
r[0][0] = (V_selected[4]/alfa)/gamma
r[0][1] = (V_selected[5]/alfa)/gamma
r[0][2] = (V_selected[6]/alfa)/gamma
t[0] = (V_selected[7]/alfa)/gamma


In [7]:
r[2,:] = np.cross(r[0,:],r[1,:])

u,d,v = np.linalg.svd(r, full_matrices=True, compute_uv=True)
r = np.dot(np.dot(u,np.identity(3)),v)
print (r)
print (gamma,(gamma**2 *(r[1][0]**2 + r[1][1]**2 + r[1][2]**2)) ** (1/2),gamma ==(gamma**2 *(r[1][0]**2 + r[1][1]**2 + r[1][2]**2)) ** (1/2))
print (alfa*gamma,(alfa**2 *gamma**2 *(r[0][0]**2 + r[0][1]**2 + r[0][2]**2)) ** (1/2),alfa*gamma==(alfa**2*gamma**2 *(r[0][0]**2 + r[0][1]**2 + r[0][2]**2)) ** (1/2))
print (r[1][0]**2+r[1][1]**2+r[1][2]**2)
print (r[0][0]**2+r[0][1]**2+r[0][2]**2)
print (r[2][0]**2+r[2][1]**2+r[2][2]**2)
print("******************")
print (np.inner(r[2,:],r[0,:]),np.inner(r[2,:],r[1,:])) 
print("******************")
print (t)

[[ 0.95614399 -0.27906059  0.08895982]
 [ 0.19806932  0.39229317 -0.89826199]
 [ 0.21577119  0.87648802  0.4303621 ]]
0.003910468204803878 0.003910468204803878 True
0.004340722667048727 0.004340722667048727 True
1.0
1.0
0.9999999999999991
******************
2.706168622523819e-16 -2.7755575615628914e-16
******************
[[183.53431591]
 [154.5554616 ]
 [  1.        ]]


In [8]:
x_aux = imgpoints[1][0] * (r[0][0] * worldpoints[1][0] + r[0][1] * worldpoints[1][1] +
                                    r[0][2] * worldpoints[1][2] + t[0])

# print(x_aux,imgpoints[0][1][0][0],worldpoints[0][1],imgpoints[0][1][0][1] )
if x_aux > 0:
    r[0,:] = -r[0,:]
    r[1,:] = -r[1,:]
    t[0:2] = -t[0:2]

A_2 = []
# for worldpoint_vector,imgpoints_vector in zip(worldpoints,imgpoints):
for worldpoint,imgpoint in zip(worldpoints,imgpoints):
    A_line = []
    A_line.append(imgpoint[0])
    A_line.append(r[0][0] * worldpoint[0] + r[0][1] * worldpoint[1] + r[0][2] * worldpoint[2] + t[0][0])
    A_2.append(A_line)

A_2 = np.asarray(A_2)
# print (A_2.shape)
b = []
# for worldpoint_vector,imgpoints_vector in zip(worldpoints,imgpoints):
for worldpoint,imgpoint in zip(worldpoints,imgpoints):
        b.append(-imgpoint[0]* (r[2][0] * worldpoint[0] + r[2][1] * worldpoint[1] + r[2][2] * worldpoint[2]))

b = np.asarray(b)
# t[0][0]

In [9]:
tf = np.dot(np.linalg.pinv(A_2),b)
# c = A_2[1][0]*tz+A_2[1][1]*fx
c = np.dot(A_2[2],tf)
# print (c,b[1],c/b[1],c*(b[1]/c),b[1])
c = c/b[2]
print(c,tf/c)

1.1671104345827192 [ 286.77342295 3333.65930462]
